### ISSUE TITLE
启动报错

### ISSUE THREAD

**Issue by luganhuo** [blue-troy/91porn-crawler#25]
通过第一种方式启动报错

2019-03-28 02:00:01.746 |-ERROR [main] org.springframework.boot.SpringApplication [858] -| Application run failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'persistenceAspect' defined in URL [jar:file:/D:/crawler91.jar!/BOOT-INF/lib/default-crawler-0.0.1-SNAPSHOT.jar!/club/bluetroy/crawler/persistence/PersistenceAspect.class]: Instantiation of bean failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [club.bluetroy.crawler.persistence.PersistenceAspect]: Constructor threw exception; nested exception is java.nio.file.InvalidPathException: Illegal char <:> at index 4: file:/D:/crawler91.jar!/BOOT-INF/classes!/
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateBean(AbstractAutowireCapableBeanFactory.java:1270) ~[spring-beans-5.1.4.RELEASE.jar!/:5.1.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1164) ~[spring-beans-5.1.4.RELEASE.jar!/:5.1.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:538) ~[spring-beans-5.1.4.RELEASE.jar!/:5.1.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:498) ~[spring-beans-5.1.4.RELEASE.jar!/:5.1.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320) ~[spring-beans-5.1.4.RELEASE.jar!/:5.1.4.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222) ~[spring-beans-5.1.4.RELEASE.jar!/:5.1.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318) ~[spring-beans-5.1.4.RELEASE.jar!/:5.1.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199) ~[spring-beans-5.1.4.RELEASE.jar!/:5.1.4.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:846) ~[spring-beans-5.1.4.RELEASE.jar!/:5.1.4.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:863) ~[spring-context-5.1.4.RELEASE.jar!/:5.1.4.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:546) ~[spring-context-5.1.4.RELEASE.jar!/:5.1.4.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:142) ~[spring-boot-2.1.2.RELEASE.jar!/:2.1.2.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:775) [spring-boot-2.1.2.RELEASE.jar!/:2.1.2.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397) [spring-boot-2.1.2.RELEASE.jar!/:2.1.2.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:316) [spring-boot-2.1.2.RELEASE.jar!/:2.1.2.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1260) [spring-boot-2.1.2.RELEASE.jar!/:2.1.2.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1248) [spring-boot-2.1.2.RELEASE.jar!/:2.1.2.RELEASE]
	at club.bluetroy.Crawler91Application.main(Crawler91Application.java:17) [classes!/:0.0.1-SNAPSHOT]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48) [crawler91.jar:0.0.1-SNAPSHOT]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) [crawler91.jar:0.0.1-SNAPSHOT]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50) [crawler91.jar:0.0.1-SNAPSHOT]
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51) [crawler91.jar:0.0.1-SNAPSHOT]
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [club.bluetroy.crawler.persistence.PersistenceAspect]: Constructor threw exception; nested exception is java.nio.file.InvalidPathException: Illegal char <:> at index 4: file:/D:/crawler91.jar!/BOOT-INF/classes!/
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:184) ~[spring-beans-5.1.4.RELEASE.jar!/:5.1.4.RELEASE]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:87) ~[spring-beans-5.1.4.RELEASE.jar!/:5.1.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateBean(AbstractAutowireCapableBeanFactory.java:1262) ~[spring-beans-5.1.4.RELEASE.jar!/:5.1.4.RELEASE]
	... 25 more
Caused by: java.nio.file.InvalidPathException: Illegal char <:> at index 4: file:/D:/crawler91.jar!/BOOT-INF/classes!/
	at sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182) ~[?:?]
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153) ~[?:?]
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77) ~[?:?]
	at sun.nio.fs.WindowsPath.parse(WindowsPath.java:92) ~[?:?]
	at sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:229) ~[?:?]
	at java.nio.file.Path.of(Path.java:147) ~[?:?]
	at java.nio.file.Paths.get(Paths.java:69) ~[?:?]
	at club.bluetroy.crawler.persistence.PersistenceAspect.<init>(PersistenceAspect.java:35) ~[default-crawler-0.0.1-SNAPSHOT.jar!/:0.0.1-SNAPSHOT]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:490) ~[?:?]
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:172) ~[spring-beans-5.1.4.RELEASE.jar!/:5.1.4.RELEASE]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:87) ~[spring-beans-5.1.4.RELEASE.jar!/:5.1.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateBean(AbstractAutowireCapableBeanFactory.java:1262) ~[spring-beans-5.1.4.RELEASE.jar!/:5.1.4.RELEASE]
	... 25 more
2019-03-28 02:00:39.552 |-ERROR [main] org.springframework.boot.SpringApplication [858] -| Application run failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'persistenceAspect' defined in URL [jar:file:/D:/crawler91.jar!/BOOT-INF/lib/default-crawler-0.0.1-SNAPSHOT.jar!/club/bluetroy/crawler/persistence/PersistenceAspect.class]: Instantiation of bean failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [club.bluetroy.crawler.persistence.PersistenceAspect]: Constructor threw exception; nested exception is java.nio.file.InvalidPathException: Illegal char <:> at index 4: file:/D:/crawler91.jar!/BOOT-INF/classes!/
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateBean(AbstractAutowireCapableBeanFactory.java:1270) ~[spring-beans-5.1.4.RELEASE.jar!/:5.1.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1164) ~[spring-beans-5.1.4.RELEASE.jar!/:5.1.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:538) ~[spring-beans-5.1.4.RELEASE.jar!/:5.1.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:498) ~[spring-beans-5.1.4.RELEASE.jar!/:5.1.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320) ~[spring-beans-5.1.4.RELEASE.jar!/:5.1.4.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222) ~[spring-beans-5.1.4.RELEASE.jar!/:5.1.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318) ~[spring-beans-5.1.4.RELEASE.jar!/:5.1.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199) ~[spring-beans-5.1.4.RELEASE.jar!/:5.1.4.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:846) ~[spring-beans-5.1.4.RELEASE.jar!/:5.1.4.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:863) ~[spring-context-5.1.4.RELEASE.jar!/:5.1.4.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:546) ~[spring-context-5.1.4.RELEASE.jar!/:5.1.4.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:142) ~[spring-boot-2.1.2.RELEASE.jar!/:2.1.2.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:775) [spring-boot-2.1.2.RELEASE.jar!/:2.1.2.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397) [spring-boot-2.1.2.RELEASE.jar!/:2.1.2.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:316) [spring-boot-2.1.2.RELEASE.jar!/:2.1.2.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1260) [spring-boot-2.1.2.RELEASE.jar!/:2.1.2.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1248) [spring-boot-2.1.2.RELEASE.jar!/:2.1.2.RELEASE]
	at club.bluetroy.Crawler91Application.main(Crawler91Application.java:17) [classes!/:0.0.1-SNAPSHOT]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48) [crawler91.jar:0.0.1-SNAPSHOT]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) [crawler91.jar:0.0.1-SNAPSHOT]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50) [crawler91.jar:0.0.1-SNAPSHOT]
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51) [crawler91.jar:0.0.1-SNAPSHOT]
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [club.bluetroy.crawler.persistence.PersistenceAspect]: Constructor threw exception; nested exception is java.nio.file.InvalidPathException: Illegal char <:> at index 4: file:/D:/crawler91.jar!/BOOT-INF/classes!/
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:184) ~[spring-beans-5.1.4.RELEASE.jar!/:5.1.4.RELEASE]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:87) ~[spring-beans-5.1.4.RELEASE.jar!/:5.1.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateBean(AbstractAutowireCapableBeanFactory.java:1262) ~[spring-beans-5.1.4.RELEASE.jar!/:5.1.4.RELEASE]
	... 25 more
Caused by: java.nio.file.InvalidPathException: Illegal char <:> at index 4: file:/D:/crawler91.jar!/BOOT-INF/classes!/
	at sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182) ~[?:?]
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153) ~[?:?]
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77) ~[?:?]
	at sun.nio.fs.WindowsPath.parse(WindowsPath.java:92) ~[?:?]
	at sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:229) ~[?:?]
	at java.nio.file.Path.of(Path.java:147) ~[?:?]
	at java.nio.file.Paths.get(Paths.java:69) ~[?:?]
	at club.bluetroy.crawler.persistence.PersistenceAspect.<init>(PersistenceAspect.java:35) ~[default-crawler-0.0.1-SNAPSHOT.jar!/:0.0.1-SNAPSHOT]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:490) ~[?:?]
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:172) ~[spring-beans-5.1.4.RELEASE.jar!/:5.1.4.RELEASE]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:87) ~[spring-beans-5.1.4.RELEASE.jar!/:5.1.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateBean(AbstractAutowireCapableBeanFactory.java:1262) ~[spring-beans-5.1.4.RELEASE.jar!/:5.1.4.RELEASE]
	... 25 more

**Comment by blue-troy** [comment]
能否说明什么是“第一种方式” ？ @luganhuo

**Comment by masakacj** [comment]
有同样的问题，双击jar运行或者命令行运行都会有错误

**Comment by blue-troy** [comment]
你的java版本是？ @masakacj @luganhuo

**Comment by masakacj** [comment]
jdk 11.0.2

**Comment by blue-troy** [comment]
@masakacj 
我当前在如下环境：
```
os: macos 10.14.4
java version "11" 2018-09-25
Java(TM) SE Runtime Environment 18.9 (build 11+28)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11+28, mixed mode)
```
使用release-0.0.2 snapshot版本测试通过.


你是下载的release 还是自己编译的,能否使用 java -version命令展示以下具体的java版本,以及操作系统环境以帮助我排查问题呢？

**Comment by masakacj** [comment]
我是直接下载的release中crawler91.jar运行的

java version "11.0.2" 2019-01-15 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.2+9-LTS)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.2+9-LTS, mixed mode)

OS是win10 64位

**Comment by blue-troy** [comment]
@masakacj 
好的，稍后我会在相应环境进行测试，测试完成后会告知。
同时请确认下载的版本为最新的0.0.2-SNAPSHOT 版本。

**Comment by masakacj** [comment]
嗯，确认是最新版

**Comment by bigfans233** [comment]
6666

**Comment by Hyper-Beast** [comment]
> 经过测试发现确实windows无法启动项目,原因应该是windows对于文件路径的不同处理。将在下一个版本处理这个问题 @luganhuo @masakacj

请问这个问题还没解决吗，我也遇到一样的问题了

**Comment by blue-troy** [comment]
> > 经过测试发现确实windows无法启动项目,原因应该是windows对于文件路径的不同处理。将在下一个版本处理这个问题 @luganhuo @masakacj
> 
> 请问这个问题还没解决吗，我也遇到一样的问题了

你用的哪个分支的版本?

**Comment by Hyper-Beast** [comment]
> > > 经过测试发现确实windows无法启动项目,原因应该是windows对于文件路径的不同处理。将在下一个版本处理这个问题 @luganhuo @masakacj
> > 
> > 
> > 请问这个问题还没解决吗，我也遇到一样的问题了
> 
> 你用的哪个分支的版本?

我就是下载的0.02release的版本，源代码不知道怎么运行

**Comment by blue-troy** [comment]
> > > > 经过测试发现确实windows无法启动项目,原因应该是windows对于文件路径的不同处理。将在下一个版本处理这个问题 @luganhuo @masakacj
> > > 
> > > 
> > > 请问这个问题还没解决吗，我也遇到一样的问题了
> > 
> > 
> > 你用的哪个分支的版本?
> 
> 我就是下载的0.02release的版本，源代码不知道怎么运行

这个版本没有修复windows不能使用的bug哦

**Comment by Hyper-Beast** [comment]
> > > > > 经过测试发现确实windows无法启动项目,原因应该是windows对于文件路径的不同处理。将在下一个版本处理这个问题 @luganhuo @masakacj
> > > > 
> > > > 
> > > > 请问这个问题还没解决吗，我也遇到一样的问题了
> > > 
> > > 
> > > 你用的哪个分支的版本?
> > 
> > 
> > 我就是下载的0.02release的版本，源代码不知道怎么运行
> 
> 这个版本没有修复windows不能使用的bug哦

换了Linux是能启动了，但是也没法用，一点开始就提示与服务器失去连接，然后地址什么也没法设置
![image](https://user-images.githubusercontent.com/18001712/124279232-d53cf600-db79-11eb-97cc-e0417ca54974.png)

**Comment by blue-troy** [comment]
> > > > > > 经过测试发现确实windows无法启动项目,原因应该是windows对于文件路径的不同处理。将在下一个版本处理这个问题 @luganhuo @masakacj
> > > > > 
> > > > > 
> > > > > 请问这个问题还没解决吗，我也遇到一样的问题了
> > > > 
> > > > 
> > > > 你用的哪个分支的版本?
> > > 
> > > 
> > > 我就是下载的0.02release的版本，源代码不知道怎么运行
> > 
> > 
> > 这个版本没有修复windows不能使用的bug哦
> 
> 换了Linux是能启动了，但是也没法用，一点开始就提示与服务器失去连接，然后地址什么也没法设置
> ![image](https://user-images.githubusercontent.com/18001712/124279232-d53cf600-db79-11eb-97cc-e0417ca54974.png)

应该要配置代理吧
