### ISSUE TITLE
代理问题

### ISSUE THREAD

**Issue by jingb** [blue-troy/91porn-crawler#26]
shadowsock代理正常  可以打开墙外网站
shadowsock监听着1087端口    代理设置了127.0.0.1:1087
还是下载失败  

2019-04-27 21:04:03.449 |-INFO  [DOWNLOAD-pool-0] club.bluetroy.crawler.util.HttpClient [36] -| getNow  http://91porn.com/view_video.php?viewkey=f9f505bea42ef942b6a9&page=1&viewtype=basic&category=hot
2019-04-27 21:04:04.467 |-INFO  [DOWNLOAD-pool-0] club.bluetroy.crawler.DefaultDownloader [50] -| 下载失败
java.lang.NullPointerException: null
	at club.bluetroy.crawler.tool.Selector.getDownloadUrl(Selector.java:63) ~[default-crawler-0.0.1-SNAPSHOT.jar!/:0.0.1-SNAPSHOT]
	at club.bluetroy.crawler.tool.ScannerTool.scanDownloadUrl(ScannerTool.java:64) ~[default-crawler-0.0.1-SNAPSHOT.jar!/:0.0.1-SNAPSHOT]
	at club.bluetroy.crawler.DefaultScanner.getDownloadUrl(DefaultScanner.java:63) ~[default-crawler-0.0.1-SNAPSHOT.jar!/:0.0.1-SNAPSHOT]
	at club.bluetroy.crawler.DefaultScanner$$FastClassBySpringCGLIB$$afa270ab.invoke(<generated>) ~[default-crawler-0.0.1-SNAPSHOT.jar!/:0.0.1-SNAPSHOT]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.1.4.RELEASE.jar!/:5.1.4.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:749) ~[spring-aop-5.1.4.RELEASE.jar!/:5.1.4.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.1.4.RELEASE.jar!/:5.1.4.RELEASE]
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:93) ~[spring-aop-5.1.4.RELEASE.jar!/:5.1.4.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.1.4.RELEASE.jar!/:5.1.4.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:688) ~[spring-aop-5.1.4.RELEASE.jar!/:5.1.4.RELEASE]
	at club.bluetroy.crawler.DefaultScanner$$EnhancerBySpringCGLIB$$46edfff1.getDownloadUrl(<generated>) ~[default-crawler-0.0.1-SNAPSHOT.jar!/:0.0.1-SNAPSHOT]
	at club.bluetroy.crawler.DefaultDownloader.getDownloadUrl(DefaultDownloader.java:58) ~[default-crawler-0.0.1-SNAPSHOT.jar!/:0.0.1-SNAPSHOT]
	at club.bluetroy.crawler.DefaultDownloader.lambda$downloadByKey$1(DefaultDownloader.java:46) [default-crawler-0.0.1-SNAPSHOT.jar!/:0.0.1-SNAPSHOT]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
2019-04-27 21:04:04.473 |-INFO  [http-nio-8080-exec-1] club.bluetroy.controller.WebSocketController [44] -| message message {"method":"/downloadingMovies","data":{},"message":null}
2019-04-27 21:04:04.475 |-INFO  [http-nio-8080-exec-1] club.bluetroy.controller.WebSocketController [44] -| message message {"method":"/downloadedMovies","data":{},"message":null}
2019-04-27 21:04:04.480 |-INFO  [http-nio-8080-exec-1] club.bluetroy.controller.WebSocketController [44] -| message message {"method":"/downloadErrorMovies","data":{"f9f505bea42ef942b6a9":{"title":"炮椅输出【成人抖音快手APP】酒店偷拍看涧介","length":"10:28","addTime":"2019年4月26日22时","author":"sexbook1000","view":37840,"collect":66,"messageNumber":8,"integration":5000,"detailURL":"http://91porn.com/view_video.php?viewkey=f9f505bea42ef942b6a9&page=1&viewtype=basic&category=hot","downloadURL":null,"fileName":"炮椅输出【成人抖音快手APP】酒店偷拍看涧介.mp4","key":"f9f505bea42ef942b6a9","addDateTime":{"nano":652406000,"year":2019,"monthValue":4,"dayOfMonth":26,"hour":22,"minute":3,"second":23,"month":"APRIL","dayOfYear":116,"dayOfWeek":"FRIDAY","chronology":{"id":"ISO","calendarType":"iso8601"}}}},"message":null}
^C2019-04-27 21:04:09.655 |-INFO  [Thread-2] org.springframework.scheduling.concurrent.ThreadPoolTaskScheduler [208] -| Shutting down ExecutorService 'taskScheduler'
2019-04-27 21:04:09.656 |-INFO  [Thread-2] org.springframework.scheduling.concurrent.ThreadPoolTaskExecutor [208] -| Shutting down ExecutorService 'applicationTaskExecutor'
2019-04-27 21:04:09.658 |-INFO  [Thread-2] club.bluetroy.crawler.dao.Persistence [55] -| 马上要被销毁了 要把数据存下来
2019-04-27 21:04:09.664 |-WARN  [Thread-2] club.bluetroy.crawler.dao.Persistence [60] -| 数据保存失败
java.io.NotSerializableException: club.bluetroy.crawler.dao.entity.DownloadErrorInfo
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1185) ~[?:?]
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:349) ~[?:?]
	at java.util.concurrent.ConcurrentHashMap.writeObject(ConcurrentHashMap.java:1424) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:1130) ~[?:?]
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1497) ~[?:?]
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1433) ~[?:?]
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1179) ~[?:?]
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1553) ~[?:?]
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1510) ~[?:?]
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1433) ~[?:?]
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1179) ~[?:?]
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:349) ~[?:?]
	at club.bluetroy.crawler.dao.Persistence.persistence(Persistence.java:58) [default-crawler-0.0.1-SNAPSHOT.jar!/:0.0.1-SNAPSHOT]
	at club.bluetroy.crawler.dao.Persistence$$FastClassBySpringCGLIB$$cfd313d5.invoke(<generated>) [default-crawler-0.0.1-SNAPSHOT.jar!/:0.0.1-SNAPSHOT]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) [spring-core-5.1.4.RELEASE.jar!/:5.1.4.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:749) [spring-aop-5.1.4.RELEASE.jar!/:5.1.4.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) [spring-aop-5.1.4.RELEASE.jar!/:5.1.4.RELEASE]
	at org.springframework.aop.aspectj.AspectJAfterAdvice.invoke(AspectJAfterAdvice.java:47) [spring-aop-5.1.4.RELEASE.jar!/:5.1.4.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) [spring-aop-5.1.4.RELEASE.jar!/:5.1.4.RELEASE]
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:93) [spring-aop-5.1.4.RELEASE.jar!/:5.1.4.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) [spring-aop-5.1.4.RELEASE.jar!/:5.1.4.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:688) [spring-aop-5.1.4.RELEASE.jar!/:5.1.4.RELEASE]
	at club.bluetroy.crawler.dao.Persistence$$EnhancerBySpringCGLIB$$d192df84.persistence(<generated>) [default-crawler-0.0.1-SNAPSHOT.jar!/:0.0.1-SNAPSHOT]
	at club.bluetroy.crawler.dao.PersistentDao.persistence(PersistentDao.java:184) [default-crawler-0.0.1-SNAPSHOT.jar!/:0.0.1-SNAPSHOT]
	at club.bluetroy.crawler.dao.PersistentDao$$FastClassBySpringCGLIB$$2764bd31.invoke(<generated>) [default-crawler-0.0.1-SNAPSHOT.jar!/:0.0.1-SNAPSHOT]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) [spring-core-5.1.4.RELEASE.jar!/:5.1.4.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:749) [spring-aop-5.1.4.RELEASE.jar!/:5.1.4.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) [spring-aop-5.1.4.RELEASE.jar!/:5.1.4.RELEASE]
	at org.springframework.aop.aspectj.AspectJAfterAdvice.invoke(AspectJAfterAdvice.java:47) [spring-aop-5.1.4.RELEASE.jar!/:5.1.4.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) [spring-aop-5.1.4.RELEASE.jar!/:5.1.4.RELEASE]
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:93) [spring-aop-5.1.4.RELEASE.jar!/:5.1.4.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) [spring-aop-5.1.4.RELEASE.jar!/:5.1.4.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:688) [spring-aop-5.1.4.RELEASE.jar!/:5.1.4.RELEASE]
	at club.bluetroy.crawler.dao.PersistentDao$$EnhancerBySpringCGLIB$$53fe9518.persistence(<generated>) [default-crawler-0.0.1-SNAPSHOT.jar!/:0.0.1-SNAPSHOT]
	at club.bluetroy.crawler.dao.Persistence.save(Persistence.java:66) [default-crawler-0.0.1-SNAPSHOT.jar!/:0.0.1-SNAPSHOT]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:363) [spring-beans-5.1.4.RELEASE.jar!/:5.1.4.RELEASE]
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeDestroyMethods(InitDestroyAnnotationBeanPostProcessor.java:321) [spring-beans-5.1.4.RELEASE.jar!/:5.1.4.RELEASE]
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeDestruction(InitDestroyAnnotationBeanPostProcessor.java:156) [spring-beans-5.1.4.RELEASE.jar!/:5.1.4.RELEASE]
	at org.springframework.beans.factory.support.DisposableBeanAdapter.destroy(DisposableBeanAdapter.java:240) [spring-beans-5.1.4.RELEASE.jar!/:5.1.4.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroyBean(DefaultSingletonBeanRegistry.java:571) [spring-beans-5.1.4.RELEASE.jar!/:5.1.4.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingleton(DefaultSingletonBeanRegistry.java:543) [spring-beans-5.1.4.RELEASE.jar!/:5.1.4.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingleton(DefaultListableBeanFactory.java:1052) [spring-beans-5.1.4.RELEASE.jar!/:5.1.4.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingletons(DefaultSingletonBeanRegistry.java:504) [spring-beans-5.1.4.RELEASE.jar!/:5.1.4.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingletons(DefaultListableBeanFactory.java:1059) [spring-beans-5.1.4.RELEASE.jar!/:5.1.4.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.destroyBeans(AbstractApplicationContext.java:1035) [spring-context-5.1.4.RELEASE.jar!/:5.1.4.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.doClose(AbstractApplicationContext.java:1011) [spring-context-5.1.4.RELEASE.jar!/:5.1.4.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext$1.run(AbstractApplicationContext.java:931) [spring-context-5.1.4.RELEASE.jar!/:5.1.4.RELEASE]

**Comment by jingb** [comment]
![image](https://user-images.githubusercontent.com/9337766/56850190-80feb180-6931-11e9-8fa1-9e6e0b72b7d9.png)
楼主你发的图下面偏好设置不知道在哪打开  

mac的都是这样的
![image](https://user-images.githubusercontent.com/9337766/56850205-dc30a400-6931-11e9-86c7-ccf78cff665e.png)

**Comment by blue-troy** [comment]
@jingb shadowsocks->偏好设置->http. 中设置好http代理。
因为爬虫这边走的是http协议需要使用http代理。
目前还没有测试过shadowsocks默认的socks5代理。

**Comment by jingb** [comment]
@blue-troy    确认了ss已经开了http代理  netstat 端口正常监听   
点开始可以扫描出20条数据但是下载还是失败    换了个端口也不行   
用的是release里的jar包

**Comment by jingb** [comment]
代码 document.selectFirst("source").attr("src");   报空指针异常  
按我理解是html界面的格式改了   
document.selectFirst("source")  没找到节点

**Comment by blue-troy** [comment]
@jingb 

好的 非常感谢你的反馈,有空我会检查一下,检查完毕会给你反馈。
