### ISSUE TITLE
91下载是不是失效了？

### ISSUE THREAD

**Issue by sewujishipin** [blue-troy/91porn-crawler#29]
91下载是不是失效了？

**Comment by blue-troy** [comment]
错误代码发出来看一下

**Comment by sewujishipin** [comment]
我可以加您好友么？下载成功付费~




------------------ 原始邮件 ------------------
发件人: "blue-troy"<notifications@github.com>;
发送时间: 2019年8月12日(星期一) 下午5:44
收件人: "blue-troy/91porn-crawler"<91porn-crawler@noreply.github.com>;
抄送: "Express-FFmpeg"<1119282308@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [blue-troy/91porn-crawler] 91下载是不是失效了？ (#29)




错误代码发出来看一下

**Comment by sewujishipin** [comment]
Microsoft Windows [版本 6.3.9600]
(c) 2013 Microsoft Corporation。保留所有权利。

C:\Users\Administrator>cd /d C:\Program Files\Java\jdk-11.0.4\bin

C:\Program Files\Java\jdk-11.0.4\bin>java -jar crawler91.jar

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::        (v2.1.2.RELEASE)

2019-08-12 22:27:17.464 |-INFO  [main] club.bluetroy.Crawler91Application [50] -
| Starting Crawler91Application v0.0.1-SNAPSHOT on WIN-I35784GHMVD with PID 84 (
C:\Program Files\Java\jdk-11.0.4\bin\crawler91.jar started by Administrator in C
:\Program Files\Java\jdk-11.0.4\bin)
2019-08-12 22:27:17.636 |-INFO  [main] club.bluetroy.Crawler91Application [675]
-| No active profile set, falling back to default profiles: default
2019-08-12 22:27:20.839 |-INFO  [main] org.springframework.boot.web.embedded.tom
cat.TomcatWebServer [90] -| Tomcat initialized with port(s): 8080 (http)
2019-08-12 22:27:20.886 |-INFO  [main] org.apache.coyote.http11.Http11NioProtoco
l [173] -| Initializing ProtocolHandler ["http-nio-8080"]
2019-08-12 22:27:20.933 |-INFO  [main] org.apache.catalina.core.StandardService
[173] -| Starting service [Tomcat]
2019-08-12 22:27:20.933 |-INFO  [main] org.apache.catalina.core.StandardEngine [
173] -| Starting Servlet engine: [Apache Tomcat/9.0.14]
2019-08-12 22:27:20.948 |-INFO  [main] org.apache.catalina.core.AprLifecycleList
ener [173] -| The APR based Apache Tomcat Native library which allows optimal pe
rformance in production environments was not found on the java.library.path: [C:
\Program Files\Java\jdk-11.0.4\bin;C:\Windows\Sun\Java\bin;C:\Windows\system32;C
:\Windows;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\Sys
tem32\WindowsPowerShell\v1.0\;C:\Users\Administrator\AppData\Local\Programs\Pyth
on\Python37\Scripts\;C:\Users\Administrator\AppData\Local\Programs\Python\Python
37\;.]
2019-08-12 22:27:21.120 |-INFO  [main] org.apache.catalina.core.ContainerBase.[T
omcat].[localhost].[/] [173] -| Initializing Spring embedded WebApplicationConte
xt
2019-08-12 22:27:21.120 |-INFO  [main] org.springframework.web.context.ContextLo
ader [296] -| Root WebApplicationContext: initialization completed in 3375 ms
2019-08-12 22:27:21.480 |-WARN  [main] org.springframework.boot.web.servlet.cont
ext.AnnotationConfigServletWebServerApplicationContext [554] -| Exception encoun
tered during context initialization - cancelling refresh attempt: org.springfram
ework.beans.factory.BeanCreationException: Error creating bean with name 'persis
tenceAspect' defined in URL [jar:file:/C:/Program%20Files/Java/jdk-11.0.4/bin/cr
awler91.jar!/BOOT-INF/lib/default-crawler-0.0.1-SNAPSHOT.jar!/club/bluetroy/craw
ler/persistence/PersistenceAspect.class]: Instantiation of bean failed; nested e
xception is org.springframework.beans.BeanInstantiationException: Failed to inst
antiate [club.bluetroy.crawler.persistence.PersistenceAspect]: Constructor threw
 exception; nested exception is java.nio.file.InvalidPathException: Illegal char
 <:> at index 4: file:/C:/Program%20Files/Java/jdk-11.0.4/bin/crawler91.jar!/BOO
T-INF/classes!/
2019-08-12 22:27:21.527 |-INFO  [main] club.bluetroy.crawler.dao.Persistence [55
] -| 马上要被销毁了 要把数据存下来
2019-08-12 22:27:21.589 |-WARN  [main] org.springframework.context.annotation.Co
mmonAnnotationBeanPostProcessor [164] -| Destroy method on bean with name 'persi
stence' threw an exception: org.springframework.beans.factory.BeanCreationNotAll
owedException: Error creating bean with name 'persistenceAspect': Singleton bean
 creation not allowed while singletons of this factory are in destruction (Do no
t request a bean from a BeanFactory in a destroy method implementation!)
2019-08-12 22:27:21.589 |-INFO  [main] org.apache.catalina.core.StandardService
[173] -| Stopping service [Tomcat]
2019-08-12 22:27:21.636 |-INFO  [main] org.springframework.boot.autoconfigure.lo
gging.ConditionEvaluationReportLoggingListener [142] -|

Error starting ApplicationContext. To display the conditions report re-run your
application with 'debug' enabled.
2019-08-12 22:27:21.636 |-ERROR [main] org.springframework.boot.SpringApplicatio
n [858] -| Application run failed
org.springframework.beans.factory.BeanCreationException: Error creating bean wit
h name 'persistenceAspect' defined in URL [jar:file:/C:/Program%20Files/Java/jdk
-11.0.4/bin/crawler91.jar!/BOOT-INF/lib/default-crawler-0.0.1-SNAPSHOT.jar!/club
/bluetroy/crawler/persistence/PersistenceAspect.class]: Instantiation of bean fa
iled; nested exception is org.springframework.beans.BeanInstantiationException:
Failed to instantiate [club.bluetroy.crawler.persistence.PersistenceAspect]: Con
structor threw exception; nested exception is java.nio.file.InvalidPathException
: Illegal char <:> at index 4: file:/C:/Program%20Files/Java/jdk-11.0.4/bin/craw
ler91.jar!/BOOT-INF/classes!/
        at org.springframework.beans.factory.support.AbstractAutowireCapableBean
Factory.instantiateBean(AbstractAutowireCapableBeanFactory.java:1270) ~[spring-b
eans-5.1.4.RELEASE.jar!/:5.1.4.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBean
Factory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1164) ~[sprin
g-beans-5.1.4.RELEASE.jar!/:5.1.4.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBean
Factory.doCreateBean(AbstractAutowireCapableBeanFactory.java:538) ~[spring-beans
-5.1.4.RELEASE.jar!/:5.1.4.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBean
Factory.createBean(AbstractAutowireCapableBeanFactory.java:498) ~[spring-beans-5
.1.4.RELEASE.jar!/:5.1.4.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$
doGetBean$0(AbstractBeanFactory.java:320) ~[spring-beans-5.1.4.RELEASE.jar!/:5.1
.4.RELEASE]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistr
y.getSingleton(DefaultSingletonBeanRegistry.java:222) ~[spring-beans-5.1.4.RELEA
SE.jar!/:5.1.4.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBe
an(AbstractBeanFactory.java:318) ~[spring-beans-5.1.4.RELEASE.jar!/:5.1.4.RELEAS
E]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean
(AbstractBeanFactory.java:199) ~[spring-beans-5.1.4.RELEASE.jar!/:5.1.4.RELEASE]

        at org.springframework.beans.factory.support.DefaultListableBeanFactory.
preInstantiateSingletons(DefaultListableBeanFactory.java:846) ~[spring-beans-5.1
.4.RELEASE.jar!/:5.1.4.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.finish
BeanFactoryInitialization(AbstractApplicationContext.java:863) ~[spring-context-
5.1.4.RELEASE.jar!/:5.1.4.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.refres
h(AbstractApplicationContext.java:546) ~[spring-context-5.1.4.RELEASE.jar!/:5.1.
4.RELEASE]
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicat
ionContext.refresh(ServletWebServerApplicationContext.java:142) ~[spring-boot-2.
1.2.RELEASE.jar!/:2.1.2.RELEASE]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.
java:775) [spring-boot-2.1.2.RELEASE.jar!/:2.1.2.RELEASE]
        at org.springframework.boot.SpringApplication.refreshContext(SpringAppli
cation.java:397) [spring-boot-2.1.2.RELEASE.jar!/:2.1.2.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java
:316) [spring-boot-2.1.2.RELEASE.jar!/:2.1.2.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java
:1260) [spring-boot-2.1.2.RELEASE.jar!/:2.1.2.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java
:1248) [spring-boot-2.1.2.RELEASE.jar!/:2.1.2.RELEASE]
        at club.bluetroy.Crawler91Application.main(Crawler91Application.java:17)
 [classes!/:0.0.1-SNAPSHOT]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAcce
ssorImpl.java:62) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMe
thodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner
.java:48) [crawler91.jar:0.0.1-SNAPSHOT]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) [cr
awler91.jar:0.0.1-SNAPSHOT]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:50) [cr
awler91.jar:0.0.1-SNAPSHOT]
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
 [crawler91.jar:0.0.1-SNAPSHOT]
Caused by: org.springframework.beans.BeanInstantiationException: Failed to insta
ntiate [club.bluetroy.crawler.persistence.PersistenceAspect]: Constructor threw
exception; nested exception is java.nio.file.InvalidPathException: Illegal char
<:> at index 4: file:/C:/Program%20Files/Java/jdk-11.0.4/bin/crawler91.jar!/BOOT
-INF/classes!/
        at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:1
84) ~[spring-beans-5.1.4.RELEASE.jar!/:5.1.4.RELEASE]
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy
.instantiate(SimpleInstantiationStrategy.java:87) ~[spring-beans-5.1.4.RELEASE.j
ar!/:5.1.4.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBean
Factory.instantiateBean(AbstractAutowireCapableBeanFactory.java:1262) ~[spring-b
eans-5.1.4.RELEASE.jar!/:5.1.4.RELEASE]
        ... 25 more
Caused by: java.nio.file.InvalidPathException: Illegal char <:> at index 4: file
:/C:/Program%20Files/Java/jdk-11.0.4/bin/crawler91.jar!/BOOT-INF/classes!/
        at sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182) ~[
?:?]
        at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153) ~[?:?]

        at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77) ~[?:?]
        at sun.nio.fs.WindowsPath.parse(WindowsPath.java:92) ~[?:?]
        at sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:229) ~[?:
?]
        at java.nio.file.Path.of(Path.java:147) ~[?:?]
        at java.nio.file.Paths.get(Paths.java:69) ~[?:?]
        at club.bluetroy.crawler.persistence.PersistenceAspect.<init>(Persistenc
eAspect.java:35) ~[default-crawler-0.0.1-SNAPSHOT.jar!/:0.0.1-SNAPSHOT]
        at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Nativ
e Method) ~[?:?]
        at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(Native
ConstructorAccessorImpl.java:62) ~[?:?]
        at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(De
legatingConstructorAccessorImpl.java:45) ~[?:?]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:490) ~[?:?
]
        at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:1
72) ~[spring-beans-5.1.4.RELEASE.jar!/:5.1.4.RELEASE]
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy
.instantiate(SimpleInstantiationStrategy.java:87) ~[spring-beans-5.1.4.RELEASE.j
ar!/:5.1.4.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBean
Factory.instantiateBean(AbstractAutowireCapableBeanFactory.java:1262) ~[spring-b
eans-5.1.4.RELEASE.jar!/:5.1.4.RELEASE]
        ... 25 more

C:\Program Files\Java\jdk-11.0.4\bin>

**Comment by blue-troy** [comment]
这是一个bug 在bug修复前无法在windows系统下运行[https://github.com/blue-troy/91porn-crawler/issues/25](url)

**Comment by sewujishipin** [comment]
只有linux或者macos可以运行是么？ 还是只有macos可以运行




------------------ 原始邮件 ------------------
发件人: "blue-troy"<notifications@github.com>;
发送时间: 2019年8月12日(星期一) 晚上10:33
收件人: "blue-troy/91porn-crawler"<91porn-crawler@noreply.github.com>;
抄送: "Express-FFmpeg"<1119282308@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [blue-troy/91porn-crawler] 91下载是不是失效了？ (#29)




这是一个bug 在bug修复前无法在windows系统下运行https://github.com/blue-troy/91porn-crawler/issues/25

**Comment by blue-troy** [comment]
linux mac可以 windows不行。因为windows对于目录的处理和类unix(linux mac)有区别。不是大bug，有空的化你可以改一下我的代码解决一下这个问题，然后把你改的代码推送上来

**Comment by sewujishipin** [comment]
好的~本地没有ide，等我回去了我可以尝试修改下~因为只会php ~ java一窍不通~  感谢作者无私奉献~

**Comment by blue-troy** [comment]
这个项目有两个branch 一个master 一个sqlite jpa 可能那个branch没有这个问题，但是那个版本的功能也是不全，都是没开发完的
